#! /bin/sh

### BEGIN INIT INFO
# Provides:          statusdisplay
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start xplash screen at boot time
# Description:       Enable display service for openHAB.
### END INIT INFO

GPIO_NUM=18
PIPE_PATH="/run/xsplash/mkfifo"

. /lib/lsb/init-functions

case "$1" in
  start)
        # Export the backlight gpio and enable the backlight
        gpioset gpiochip0 $GPIO_NUM=1

        mkdir -p /run/xsplash

        if [ ! -p "$PIPE_PATH" ]; then
          mkfifo $PIPE_PATH
        fi
        chmod 0666 /run/xsplash/mkfifo

        # Start psplash tool
        #/usr/local/bin/psplash -n --fbdev 0
	;;
  stop)
        killall psplash
        echo $GPIO_NUM > /sys/class/gpio/unexport
	;;

  reload|force-reload)
	;;

  restart)
	;;

  try-restart)
	;;

  status)
        log_action_msg "statusdisplay OK"
	;;

  *)
	log_action_msg "Usage: /etc/init.d/statusdisplay {start|stop|reload|force-reload|restart|try-restart|status}" || true
	exit 1
esac

exit 0
